name: Build Image (edge)

on:
  schedule:
    - cron: '0 14 * * *' # Midnight AEST
  workflow_dispatch:

jobs:
  buildx:
    name: Build  Image (edge)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64,arm

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Compile Multipaper JARs
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: false
          target: build
          cache-from: |
            type=gha,scope=build
          cache-to: |
            type=gha,scope=build,mode=max

      - name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: false
          target: base
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: |
            type=gha,scope=base
          cache-to: |
            type=gha,scope=base,mode=max

      - name: Build multipaper-master image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: noevidenz/multipaper-master:edge
          target: master
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: |
            type=gha,scope=master
            type=gha,scope=base
            type=gha,scope=build
          cache-to: |
            type=gha,scope=master,mode=max

      - name: Build multipaper image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: noevidenz/multipaper:edge
          target: server
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: |
            type=gha,scope=server
            type=gha,scope=base
            type=gha,scope=build
          cache-to: |
            type=gha,scope=server,mode=max
